name: Convert Markdown to PDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:2.9
        with: # needs a README in your repo root!
          args: "-f markdown -t pdf Current_Constitution.md"
          # args: "--standalone --output=README.pdf README.md"
