name: Convert Markdown to PDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: "-f markdown -t Current_Constitution.md" # gets appended to pandoc command
